### ISSUE TITLE
Error on load in 10.0 prepatch

### ISSUE THREAD

**Issue by Malivil** [KeldorDE/Titan-Panel-Farm-Buddy#3]
It seems to be working for what I have configured already so not sure what's broken, but it does show this error every time I load in to the game:

> Message: Interface/AddOns/TitanFarmBuddy/TitanFarmBuddy.lua:133: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Thu Oct 27 15:44:03 2022
Count: 1
Stack: Interface/AddOns/TitanFarmBuddy/TitanFarmBuddy.lua:133: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/Bartender4/libs/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...e/AddOns/Bartender4/libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/Bartender4/libs/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/TitanFarmBuddy/TitanFarmBuddy.lua"]:133: in function <Interface/AddOns/TitanFarmBuddy/TitanFarmBuddy.lua:132>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
Locals: <none>

EDIT: I realized later that this function is what handles setting the tracked items via ALT+Right-Click in your inventory, so that isn't working right now

**Comment by KeldorDE** [comment]
Thanks for providing the fix. The release should be available on Curseforge soon 👍
